# Data Analysis
This Jupyter Notebook analyzes the errors of scenarios and transactions that were generated by different large language models.

## Table of Contents
    1. Distribution of Scenario Errors
      1.1. Distribution of Scenario Errors for each Model
    2. Distribution of Transaction Errors
      2.1. Distribution of Transaction Errors for each Model
    3. Distribution of Scenario Error Groups
    4. Distribution of Transaction Error Groups
    5. Combinations of Scenario and Transaction Error Groups
      5.1. Combinations of Scenario and Transaction Error Groups for each Model
    6. Correct Scenario and Transaction Combinations

In [28]:
import pandas as pd
#df = pd.read_csv("results/csv-files/4_scenarios_evaluated.csv")
df = pd.read_csv("D:/Studium/Master/MasterThesis/ToPublish/results/csv-files/4_scenarios_evaluated.csv")

In [29]:
df.head()

,ID,Scenario,Transaction,Transaction_Error,Scenario_Class,Transaction_Class,Scenario_Error
0,CodeL-CaR-Airbus06,NaN,NaN,Missing Transaction,missing,missing,missing scenario
1,CodeL-CaR-Airbus08,NaN,NaN,Missing Transaction,missing,missing,missing scenario
2,CodeL-CaR-Airbus10,NaN,NaN,Missing Transaction,missing,missing,missing scenario
3,CodeL-CaR-Airbus18,NaN,NaN,Missing Transaction,missing,missing,missing scenario
4,CodeL-CaR-Bayer05,The company uses 50% of its cash reserves to c...,NaN,Missing Transaction,incomplete,missing,missing effect

### 1. Distribution of Scenario Errors

In [5]:
round(df["Scenario_Error"].value_counts()/len(df),4)*100

Scenario_Error
missing scenario        33.67
unspecified accounts    28.33
incorrect scenario      14.33
correct                 11.67
missing effect           6.33
incorrect effect         5.67
Name: count, dtype: float64

#### 1.1. Distribution of Scenario Errors for each Model

In [24]:
models = ["CodeL", "CodeQ", "Mistral", "Llama", "Qwen"]

for model in models:
    model_df = df[df["ID"].str.contains(model)]
    print(f"Distribution of Scenario Errors for {model}:")
    print(round(model_df["Scenario_Error"].value_counts()/len(model_df),4)*100,"\n--------------------------------")

Distribution of Scenario Errors for CodeL:
Scenario_Error
missing scenario    68.33
missing effect      31.67
Name: count, dtype: float64
--------------------------------
Distribution of Scenario Errors for CodeQ:
Scenario_Error
missing scenario    100.0
Name: count, dtype: float64
--------------------------------
Distribution of Scenario Errors for Mistral:
Scenario_Error
unspecified accounts    58.33
incorrect scenario      21.67
correct                 20.00
Name: count, dtype: float64
--------------------------------
Distribution of Scenario Errors for Llama:
Scenario_Error
unspecified accounts    51.67
incorrect scenario      23.33
correct                 16.67
incorrect effect         8.33
Name: count, dtype: float64
--------------------------------
Distribution of Scenario Errors for Qwen:
Scenario_Error
unspecified accounts    31.67
incorrect scenario      26.67
correct                 21.67
incorrect effect        20.00
Name: count, dtype: float64
--------------------------------

### 2. Distribution of Transaction Errors

In [32]:
def transaction_error_classification(df):
    # Count transaction errors
    missing_count = df['Transaction_Error'].str.contains('Missing Transaction', na=False).sum()*100
    balance_count = (df['Transaction_Error'].str.contains('Transaction does not balance', na=False) & ~df['Transaction_Error'].str.contains('Invalid reference to unknown account', na=False)).sum()*100
    unknown_account_count = df['Transaction_Error'].str.contains('Invalid reference to unknown account', na=False).sum()*100
    syntax_count = df['Transaction_Error'].str.contains('syntax error', na=False).sum()*100
    compiles_incorrect_count = (df['Transaction_Error'].isna() & (df['Transaction_Class'] != 'correct')).sum()*100
    compiles_correct_count = df[df['Transaction_Class']=='correct']['Transaction_Class'].count()*100

    print(f"Missing error: {round(missing_count/len(df), 2)}\nBalance error: {round(balance_count/len(df), 2)}\nUnknown account error: {round(unknown_account_count/len(df), 2)}\nSyntax error: {round(syntax_count/len(df), 2)}\nincorrect | compiles:{round(compiles_incorrect_count/len(df), 2)}\ncorrect | compiles:{round(compiles_correct_count/len(df), 2)}\n-----------------------------------\n")

transaction_error_classification(df)

Missing error: 40.0
Balance error: 23.33
Unknown account error: 17.67
Syntax error: 0.0
incorrect | compiles:10.67
correct | compiles:8.33
-----------------------------------

#### 2.1. Distribution of Transaction Errors for each Model

In [27]:
models = ["CodeL", "CodeQ", "Mistral", "Llama", "Qwen"]
for model in models:
    model_df = df[df["ID"].str.contains(model)]
    print(f"Distribution of Transaction Errors for {model}:")
    transaction_error_classification(model_df)

Distribution of Transaction Errors for CodeL:
Missing error: 100.0
Balance error: 0.0
Unknown account error: 0.0
Syntax error: 0.0
incorrect | compiles:0.0
correct | compiles:0.0
-----------------------------------

Distribution of Transaction Errors for CodeQ:
Missing error: 100.0
Balance error: 0.0
Unknown account error: 0.0
Syntax error: 0.0
incorrect | compiles:0.0
correct | compiles:0.0
-----------------------------------

Distribution of Transaction Errors for Mistral:
Missing error: 0.0
Balance error: 16.67
Unknown account error: 45.0
Syntax error: 0.0
incorrect | compiles:28.33
correct | compiles:10.0
-----------------------------------

Distribution of Transaction Errors for Llama:
Missing error: 0.0
Balance error: 38.33
Unknown account error: 35.0
Syntax error: 0.0
incorrect | compiles:11.67
correct | compiles:15.0
-----------------------------------

Distribution of Transaction Errors for Qwen:
Missing error: 0.0
Balance error: 61.67
Unknown account error: 8.33
Syntax error: 0.0
incorrect | compiles:13.33
correct | compiles:16.67
-----------------------------------

### 3. Count of Scenario Error Groups

In [48]:
df["Scenario_Class"].value_counts()

Scenario_Class
incomplete    105
missing       101
incorrect      59
correct        35
Name: count, dtype: int64

### 4. Count of Transaction Error Groups

In [44]:
df["Transaction_Class"].value_counts()

Transaction_Class
incorrect    155
missing      120
correct       25
Name: count, dtype: int64

### 5. Combinations of Scenario and Transaction Error Groups

In [50]:
print(df.groupby(['Scenario_Class', 'Transaction_Class']).size().reset_index(name='Count'))

  Scenario_Class Transaction_Class  Count
0        correct           correct      7
1        correct         incorrect     28
2     incomplete           correct     12
3     incomplete         incorrect     74
4     incomplete           missing     19
5      incorrect           correct      6
6      incorrect         incorrect     53
7        missing           missing    101

#### 5.1. Combinations of Scenario and Transaction Error Groups for each Model

In [40]:
models = ["CodeL", "CodeQ", "Mistral", "Llama", "Qwen"]

# Group by Scenario_Class and Transaction_Class
for model in models:
    model_df = df[df["ID"].str.contains("Qwen")]
    print(f"Scenario and Transaction Error Group Combinations for {model}")
    print(model_df.groupby(['Scenario_Class', 'Transaction_Class']).size().reset_index(name='Count'))
    print("-----------------------------")

Scenario and Transaction Error Group Combinations for CodeL
  Scenario_Class Transaction_Class  Count
0        correct           correct      1
1        correct         incorrect     12
2     incomplete           correct      5
3     incomplete         incorrect     13
4      incorrect           correct      4
5      incorrect         incorrect     25
-----------------------------
Scenario and Transaction Error Group Combinations for CodeQ
  Scenario_Class Transaction_Class  Count
0        correct           correct      1
1        correct         incorrect     12
2     incomplete           correct      5
3     incomplete         incorrect     13
4      incorrect           correct      4
5      incorrect         incorrect     25
-----------------------------
Scenario and Transaction Error Group Combinations for Mistral
  Scenario_Class Transaction_Class  Count
0        correct           correct      1
1        correct         incorrect     12
2     incomplete           correct      5
3     incomplete         incorrect     13
4      incorrect           correct      4
5      incorrect         incorrect     25
-----------------------------
Scenario and Transaction Error Group Combinations for Llama
  Scenario_Class Transaction_Class  Count
0        correct           correct      1
1        correct         incorrect     12
2     incomplete           correct      5
3     incomplete         incorrect     13
4      incorrect           correct      4
5      incorrect         incorrect     25
-----------------------------
Scenario and Transaction Error Group Combinations for Qwen
  Scenario_Class Transaction_Class  Count
0        correct           correct      1
1        correct         incorrect     12
2     incomplete           correct      5
3     incomplete         incorrect     13
4      incorrect           correct      4
5      incorrect         incorrect     25
-----------------------------

### 6. Correct Scenario and Transaction Combinations

In [45]:
index = df[(df["Scenario_Class"]=='correct') & (df["Transaction_Class"]=='correct')]["Transaction"].index
for i in index:
    print(df["ID"][i])
    print(df["Scenario"][i])
    print(df["Transaction"][i],"\n-------------------------------")

Llama-CaR-Mercedes-Benz01
The company uses 1000 EUR in cash to repay current other financial liabilities.
Effect: Negative



2024-07-11 * "Repay current other financial liabilities"
  Liabilities:Current:OtherFinancialLiabilities 1000 EUR
  Assets:Current:CashAndCashEquivalents -1000 EUR
-------------------------------
Llama-CaR-Mercedes-Benz17
The company uses 2000 EUR in cash to repay current financing liabilities.
Effect: Negative



2024-06-15 * "Repay current financing liabilities"
  Liabilities:Current:FinancingLiabilities -2000 EUR
  Assets:Current:CashAndCashEquivalents 2000 EUR
-------------------------------
Llama-CaR-SAP14
The company uses 400 EUR in cash to repay current tax liabilities.
Effect: Negative



2024-07-11 * "Repay current tax liabilities"
  Liabilities:Current:TaxLiabilities 400 EUR
  Assets:Current:CashAndCashEquivalents -400 EUR
-------------------------------
Llama-CaR-SAP18
The company uses 200 EUR in cash to repay current other non-financial liabilities.
Effect: Negative



2024-07-11 * "Repay current other non-financial liabilities"
  Liabilities:Current:OtherNonFinancialLiabilities 200 EUR
  Assets:Current:CashAndCashEquivalents -200 EUR
-------------------------------
Llama-CuR-SAP01
The company uses 100 EUR in cash to repay current financial liabilities.
Effect: Positive



2024-07-11 * "Repay current financial liabilities"
  Liabilities:Current:FinancialLiabilities 100 EUR
  Assets:Current:CashAndCashEquivalents -100 EUR
-------------------------------
Mistral-CaR-Mercedes-Benz01
The company uses 1000 EUR in cash to repay current other financial liabilities.
   Effect: Negative



2024-04-01 * "Repay current other financial liabilities"
  Liabilities:Current:OtherFinancialLiabilities 1000 EUR
  Assets:Current:CashAndCashEquivalents -1000 EUR
-------------------------------
Qwen-CaR-Bayer06
The company receives 200 EUR in cash from a customer for other receivables.
Effect: Positive



2024-01-01 * "Receive cash from customer for other receivables"
  Assets:Current:OtherReceivables -200 EUR
  Assets:Current:CashAndCashEquivalents 200 EUR
-------------------------------